# Generated by Django 3.2 on 2021-11-22 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonauth', '0007_auto_20211112_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_count', models.IntegerField(verbose_name='嘗試次數')),
                ('error_count_number', models.IntegerField(verbose_name='開鎖前被鎖定次數')),
                ('lockstatus', models.IntegerField(verbose_name='鎖定狀態')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commonauth.commonuser', verbose_name='使用者ID')),
            ],
            options={
                'verbose_name': '密碼鎖定紀錄',
                'verbose_name_plural': '密碼鎖定紀錄',
            },
        ),
    ]
