# Generated by Django 3.2 on 2021-08-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='日記標題')),
                ('content', models.CharField(max_length=1024, verbose_name='日記內容')),
                ('tag', models.CharField(max_length=50, verbose_name='標籤')),
                ('moodscore', models.IntegerField(max_length=10, verbose_name='心情分數')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '日記',
                'verbose_name_plural': '日記',
            },
        ),
    ]
