# Generated by Django 3.2 on 2021-08-25 10:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commonauth', '0003_auto_20210825_1047'),
        ('diary', '0002_diary_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='uuid',
        ),
        migrations.AddField(
            model_name='diary',
            name='diaryid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commonauth.commonuser'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='moodscore',
            field=models.IntegerField(verbose_name='心情分數'),
        ),
    ]
