# Generated by Django 3.2 on 2021-08-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonauth', '0003_auto_20210825_1047'),
        ('diary', '0003_auto_20210825_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonauth.commonuser'),
        ),
    ]
