# Generated by Django 3.2 on 2021-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20210825_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='tag2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='標籤2'),
        ),
        migrations.AddField(
            model_name='diary',
            name='tag3',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='標籤3'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='標籤'),
        ),
    ]
