# Generated by Django 3.2 on 2021-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='帳號')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
                ('name', models.EmailField(blank=True, default=None, max_length=100, null=True, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性別')),
                ('birthday', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='生日')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '使用者帳號',
                'verbose_name_plural': '使用者帳號',
                'ordering': ['username'],
            },
        ),
    ]
