# Generated by Django 3.2 on 2021-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonauth', '0004_alter_commonuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='username',
            field=models.EmailField(max_length=128, unique=True, verbose_name='帳號(信箱)'),
        ),
    ]
